### ISSUE TITLE
Labels and Ids

### ISSUE THREAD

**Issue by andean00** [zHaytam/Blazor.Diagrams#27]
Hi Haytam!

I am using your library since it does almost what I need for one project that I am working on. My backend has a graph structure, with each node having 1 or more ports. The difference in my model is that you can have external ports (those connecting to other ports in other nodes) but you can also have internal ports (external ports in the node connecting to ports inside the  node).

Forgive me being so dumb, but I tried changing the node label when constructing (since I did not find a Label = or Title = or Name =, etc  in the properties)

With: 
var node1 = NewNode("A", 50, 50);
var node2 = NewNode("B", 300, 300);

- I expected to see those labels appearing in the UI, since I need to create my own labels instead of always geting "Node Title" on each node. How can I do it ? 
- Also, Is there a way someone can give an id (int) to each node and each port ?  That way instead of referring to GetPort(PortAlignment.Right) I would do GetPort(portId) instead ?
- Finally, how can I customize it in order to cover the internal node case ? 

Thanks in advance and regards !

Javier

**Comment by zHaytam** [comment]
Hello,

Did you follow this guide to create your custom node? https://blazor-diagrams.zhaytam.com/customization

The default node component will always show "Node Title" because it's not meant to be actually used, most of the time you need to create your own custom stuff.

If your `NewNode` class is your custom node, then you need to create a component for it and register them with `RegisterModelComponent`.

In your `NewNode` class (which should inherit from `NodeModel`), you can add your own  method `GetPort(int portId)` and do a simple lookup in the `Ports` property. You will of course need a custom port (that inherits from `PortModel`) to hold an `int Idx` since the default `Id` property in models are strings (guids).

If you do create a custom `PortModel`, you can choose which ports can get attached to it (`CanAttachTo)`. Using this, you can configure internal ports and external ports.

I hope this helps!
ZANID Haytam

**Comment by GeorgeS2019** [comment]
@zHaytam Are you planning an demo example with Labelled Link using e.g. LinkLabelModel and LinkLabelWidget.razor?

**Comment by zHaytam** [comment]
By labeled link do you mean a label that shows on top of the links?

**Comment by GeorgeS2019** [comment]
@zHaytam  Yes.

**Comment by zHaytam** [comment]
I am currently working on that, a demo will be available once the feature is added of course.

**Comment by GeorgeS2019** [comment]
@zHaytam  Is the code of the [sample project](https://camo.githubusercontent.com/2e0f119dc99bf76a65a53f4149614a4b3725ec5f/68747470733a2f2f692e696d6775722e636f6d2f7946585a304a4e2e706e67) available, I like to see how you implement the custom node.

**Comment by zHaytam** [comment]
I added the repository url in the README (https://github.com/zHaytam/Blazor.DatabaseDesigner).
The project isn't complete yet, I just use it to test things out.

**Comment by GeorgeS2019** [comment]
@zHaytam => I think it is excellent that you are inspired by [react-diagrams.](https://github.com/projectstorm/react-diagrams) to create something unique for Blazor. 

What I find interesting is the idea of 
- [Architecture Question](https://projectstorm.gitbook.io/react-diagrams/about-the-project/architecture-questions) , specifically with how best to implement [model versus widget ](https://projectstorm.gitbook.io/react-diagrams/about-the-project/architecture-questions#model-vs-widget)in the context of Blazor. 
- [End to End Testing ](https://projectstorm.gitbook.io/react-diagrams/about-the-project/testing#end-to-end-testing) in the context of Model versus widget

Last

I am also curious HOW you would implement the drag and drop in the context of Blazor ( e.g. your Blazor.DatabaseDesigner) for dragging a node or link icon from a side bar menu into the canvas. 

Second Last

Perhaps there is need for community to eventually share their custom node and link as Nuget packages. 
- Perhaps we could think if **isolation CSS and javascript** specific for the custom node or link within Nuget packages

**Comment by zHaytam** [comment]
I transferred your comment into a new issue so that we continue the conversation there 😄 
For now I'm closing this since @andean00 didn't answer, hopefully my explanation was okay!
