### ISSUE TITLE
Custom node link point incorrect

### ISSUE THREAD

**Issue by Aggror** [zHaytam/Blazor.Diagrams#51]
Hi,
I started using this great package but I am having difficulty achieving a custom node. The links Y coordinate is lower than the actual node port itself. My custom node is a literal copy of NodeWidget.razor and thus using default styling.  I don't have any further css styling yet. Any idea what I could be forgetting here?
` DiagramManager.RegisterModelComponent<CustomNodeModel,CustomNodeWidget>();`
![nodelinks](https://user-images.githubusercontent.com/3499539/98866976-173fed00-246e-11eb-96bb-c9fdf9a36d26.jpg)

**Comment by zHaytam** [comment]
Hello,

Are there specific steps that you do that trigger this problem? Or does the problem show from the beginning?

**Comment by Aggror** [comment]
- Pretty much straight away. New project, Fixed canvas size of 800 x 600

CustomNodeWidget.razor
```
<div class="default-node @(Node.Group != null ? "grouped" : "") @(Node.Selected ? "selected" : "")">
    Node Title
    @foreach (var port in Node.Ports)
    {
        <PortRenderer Port="port" Class="default"></PortRenderer>
    }
</div>

@code {
    [Parameter]
    public CustomNode Node { get; set; }
}
```

CustomNode.cs
 ```
 public class CustomNode : NodeModel
    {
        public CustomNode(Point position = null) : base(position)
        {
            Lines = new List<string>();
        }

        public List<string> Lines { get; set; }
    }
```

**Comment by zHaytam** [comment]
Is it possible for you to create a simple repo so that its easier to reproduce please?  
I dont see a problem with this code but maybe its the external layout that ruins it.

**Comment by KarlKeu00** [comment]
I had the same issue. It seems to occur when you have a canvas that is larger than the window and you scroll. Also, there is the error when you resize the window but the canvas only moves (e.g. in Bootstrap containern)
I have adapted the script.js file and use it like this without any problems. It might not be the best performance, but it works.
The problem is that the positions of the links are calculated with DiagramManager.Container.Top, but so far it only updates when the canvas is enlarged or reduced (js ResizeObserver).
[blazor-diagram-script.zip](https://github.com/zHaytam/Blazor.Diagrams/files/5535283/blazor-diagram-script.zip)

**Comment by KarlKeu00** [comment]
I had the same issue. It seems to occur when you have a canvas that is larger than the window and you scroll. Also, there is the error when you resize the window but the canvas only moves (e.g. in Bootstrap containern)
I have adapted the script.js file and use it like this without any problems. It might not be the best performance, but it works.
The problem is that the positions of the links are calculated with DiagramManager.Container.Top, but so far it only updates when the canvas is enlarged or reduced (js ResizeObserver).

[blazor-diagram-script.zip](https://github.com/zHaytam/Blazor.Diagrams/files/5535326/blazor-diagram-script.zip)

Tipp: You can include the attached file instead of the script.js. There are no old functions restricted
Update: Performance Fix

**Comment by Aggror** [comment]
@zHaytam 
Your last sentence got me experimenting with the layout and I managed to find the culprit.
A couple of lines above the diagram I use the following <a tag> with some bootstrap class which hides the tag, if a condition is not met. When the tag is visible, the diagram is slightly larger than the screen window. If I make the diagram height a little shorter, the problem doesnt occur.  
thanks for the help.

**Comment by zHaytam** [comment]
Hello, while I'm happy you found a solution, the actual bug still exists I believe. The library should still handle these use cases because not all pages will be as normal and simple.

I will try to reproduce this issue on my end, but if one of you guys has a repro repo ready that would be of huge help!
