### ISSUE TITLE
Resizable Node

### ISSUE THREAD

**Issue by mehdei** [zHaytam/Blazor.Diagrams#59]
Hello, it's very nice work!!
may you implement resizable function for the node element it will make the designer amazing

thanks for your efforts

**Comment by zHaytam** [comment]
Hello and thanks!
I'm not sure I understand what you mean by resizable, are you talking about clicking a node and be able to resize it? If so, then that's not what this library tries to do (at least currently), since nodes are html nodes and customized (not like svg shapes in other diagram libraries).
