### ISSUE TITLE
z index on custom node with drop down

### ISSUE THREAD

**Issue by Keyan01** [zHaytam/Blazor.Diagrams#61]
Hi, Having an issue with a custom node with a drop down, it always appears behind other nodes, is there a way (and I've tried forcing it's z-index) to make a dropdown appear above another node?

**Comment by zHaytam** [comment]
Hello, do you mean the whole node appears behind other nodes? Or just the dropdown (weird)?

**Comment by Keyan01** [comment]
Just the drop down (screenshot showing issue attached)
![zorder issue](https://user-images.githubusercontent.com/45352102/101389784-d34bd680-38b9-11eb-9280-25a31993297a.png)
)

**Comment by zHaytam** [comment]
I'm sorry but I don't understand the screenshot since I don't know your design.
Can you point out your nodes in the screenshot? Is the dropdown on the top a node of its own? If yes, do you have a node that only contains a dropdown? I can't see in the screenshot a dropdown being behind another node.

Although if your custom node is simply just a dropdown, and that node was created before another one, then it'll be behind it (the order of the rendering is the order of addition).

**Comment by Keyan01** [comment]
Ok, lets see if I can explain the picture, the "not started" and "in dev" are Custom node (type1, both are inline edit hence the pencil icon) the permission is a 2nd custom node type (in it's collapsed state it is fine as just the editor / text part shows) however in the expanded (as shown) to allow the user to select which permission(s) are required, the list is shown behind the "in dev" node. HTH (I'll look at the order they are added and see If I can use that to help)

**Comment by Keyan01** [comment]
I can solve this, as you said by ensuring I add the permission node after the 2nd "state" node (i.e. add the permission custom node after the "in dev" state node. I think I can work with this for the POC. Thanks.

**Comment by zHaytam** [comment]
Glad it helps.
I am still thinking of a better way to order items, so rest assured that this isn't a final "solution".
